[project]
name = "titanoboa"
version = "0.1.2"
description = "Experimental Vyper interpreter"
#authors = []
license = { file = "LICENSE" }
readme = "README.md"
#homepage = "https://github.com/vyperlang/titanoboa"
#repository = "https://github.com/vyperlang/titanoboa"
#documentation =

keywords = ["ethereum", "evm", "smart contract", "development"]

classifiers = ["Topic :: Software Development"]

# Requirements
dependencies = [
    "hy @ git+https://github.com/hylang/hy.git@e375827a3603e33761810495a4b15a981178dc75 ",
    "vyper @ git+https://github.com/vyperlang/vyper@5a90af4cd64be956345003807a6babc882f7aa58",
    "eth-abi",
    "py-evm",
    "eth-typing",
]


[tool.setuptools.packages.find]
include = ["boa*"]

#[dev-dependencies]
#black = { version = "^18.3-alpha.0", python = "^3.6" }
